config/routes.rb
Rails.application.routes.draw do
  
  resources :videos

  root 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	before_create :video_info
	validates :link, presence: true



	def video_info
		begin
			client = YouTubeIt::Client.new(dev_key: 'AIzaSyDPecwzHBUXnzu49P5HKWYev1GcSX8qlio' )	
			video = client.video_by(link)
			self.title = video.title
			self.duration = the_duration(video.duration)
			self.author = video.author.name
			self.likes = video.rating.likes
			self.dislikes = video.rating.dislikes
		end
	end


	def poster
		link_id = link.split("=").last
		"https://img.youtube.com/vi/#{link_id}/hqdefault.jpg"
	end


	private
	 def the_duration(t)
	 	hours = (t/3600)
	 	min = ((t - ( hours * 3600)) / 60)
	 	sec = (t - (hours * 3600) - (min * 60))

	 	hours = '0' + hours.to_s if hours.to_i < 10
	 	min = '0' + min.to_s if min.to_i < 10
  		sec = '0' + sec.to_s if sec.to_i < 10
 
        hours.to_s + ':' + min.to_s + ':' + sec.to_s

	 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.order('created_at DESC')
  end

  def new
  	@video = Video.new
  end

  def create
    @video = Video.new(video_params)

  	if @video.save
  		flash[:success] = "Video Uploaded"
  		redirect_to root_path
  	else
  		render 'new'
    end
  end







private
  def video_params
    params.require(:video).permit(:link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper

	def embed (link)
		link_id = link.split("=").last
		content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{link_id}")		 
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tube</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/videos/index.html.erb
<div class="jumbotron">
  <div class="container">
    <center>
    <h1>Share your videos </h1>
    <p>Click the button below to share your video from YouTube.</p>
    
      <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
    </center>
  </div>
</div>
 


<div id="wrapper" style="padding-bottom: 230px;">
<div class="container">
	<div class="row">
		<% @videos.each do |video| %>
		<div class="col-md-4 ">
            			<div class="row">
            				<div class="col-sm-12">
								<div class="well well-sm">
										<div class="thumb-overlay">
											 <!--<%=embed(video.link)%>-->
											 	<%=image_tag video.poster %>
										</div>
										<span class="video-title title-truncate m-t-5"><%=video.title%></span>
									</a>
									<div class="video-added">
										<%=video.author%>
									</div>
									<div class="video-views pull-left">
										<%=video.duration%>
									</div>
									<div class="video-rating pull-right no-rating">
										<span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.likes %>
                    			    <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.dislikes %>
									</div>		
									<div class="clearfix"></div>
									
								</div>				
							</div>		
							<!--/.End of Col -->	
						</div>
						<!--/.End of ROW-->
		</div>
		<!--/.END of COL-->	
		<%end%>
    </div>
	<!--/.END of ROW-->
</div>
</div>	

app/views/videos/new.html.erb
<h1><center>NEW VIDEO</center></h1>


<%= form_for @video do |f| %>
	<%= f.text_field :link %>
	<%= f.button :submit %>
<%end%>